//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.19 at 10:43:14 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.signavio.com/schema/cmmn/1.1/")
package com.signavio.schema.cmmn._1;
