//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 02:48:41 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/CMMN/20151109/CMMNDI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.omg.spec.cmmn._20151109.cmmndi;
